### ISSUE TITLE
[bdo] AutoLoot , development

### ISSUE THREAD

**Issue by netzulo** [r3peat/R3p.BDO#11]
Hi again! i was navigating around code and i was thinking about **AutoLoot** functionality, searched about this and... 

* Is autoLoot totally developed ? 

https://github.com/r3peat/R3p.BDO/blob/c1208ee0a93582b7c0661560b28145b5b42b007d/R3p.bdo.testconsole/Program.cs#L103

https://github.com/r3peat/R3p.BDO/blob/19be199445d706133cb054b87de7199f929646c1/R3p.bdo.testconsole/Imports/R3p.bdo/R3p.bdo/R3p.bdo/Automation/Loot/AutoLoot.cs#L12

* Autoloot must be included at **Settings class** ?

https://github.com/r3peat/R3p.BDO/blob/19be199445d706133cb054b87de7199f929646c1/R3p.bdo.testconsole/Imports/R3p.bdo.settings/R3p.bdo.settings/Settings.cs#L466

* Autoloot must be created keys for settings xml ? _im using AutoProcessing as example_

https://github.com/r3peat/R3p.BDO/blob/19be199445d706133cb054b87de7199f929646c1/R3p.bdo.testconsole/Imports/R3p.bdo.settings/R3p.bdo.settings/Xml.cs#L12

**Comment by r3peat** [comment]
did some testing months ago but it never went into release version

also the functionalities inside the code are prty much outdated and have to be researched and developed again to make them work

**Comment by netzulo** [comment]
umm.. can we reedit this ? i want to to develop autoGrind but i need functional code first :) can you test again and release this new code for continue development from there ?

**Comment by r3peat** [comment]
no i cant

**Comment by netzulo** [comment]
can you me give a lit of feeback, talk to me about results of testing this zone some months before, if you won't to continue , i want it , but need information, so much new code for start to write... :)

ty for your time @r3peat

**Comment by r3peat** [comment]
u have to figure it out on ur own i guess cause im not rly sure how it worked and what is needed to make it work again

**Comment by netzulo** [comment]
ok then , no problem, just i need to resolve #6 first to start this :(
