### ISSUE TITLE
[question] how to use debug.lua console

### ISSUE THREAD

**Issue by netzulo** [r3peat/R3p.BDO#22]
# Description

I really don't know if im doing something wrong if i comment this lane 

https://github.com/r3peat/R3p.BDO/blob/411464268bfc3075df11f83602e8f4cfe96d3f6f/R3p.bdo.testconsole/Program.cs#L153

if i do this, i get this behaviour at open game, opened new window named ``DEBUG lua console``

just take a look : 

![what](https://user-images.githubusercontent.com/11871932/40879346-b18fc302-669e-11e8-8da7-62578b62e750.png)

### How can i use this console @r3peat ?, and ... can't close !! xDDDDD

_close at answer please_

**Comment by r3peat** [comment]
it has nothing to do with the ActivityLog

its just the lua file inside lua folder which gets loaded

its some sort of a lua debug console which gets loaded by game's lua

u can enter straight up lua code in there to test stuff
it also shows u return values of entered code

u can use it to call game's lua functions

check decompiled lua scripts in here for actual code
https://github.com/r3peat/BDO_LuaFiles

**Comment by netzulo** [comment]
:O really usefull , never used lua, let me check it :) , thank you in advance for your time

**Comment by netzulo** [comment]
hohoho i get some return values , awesome bro @r3peat ! but...  i want to compile this too :( VS2k17 don't let me , i get 3160 errors wich have no sense xD

**Comment by netzulo** [comment]
:O then bot it's just a combination of scritps that connect lua and modify requests 🤔 

1. ``Panel_Window_Inventory:SetShow(true)``
2. ``Panel_Window_Inventory:SetShow()``
