### ISSUE TITLE
[question] DOC for lua debug ?

### ISSUE THREAD

**Issue by netzulo** [r3peat/R3p.BDO#23]
## Description

- Readed about function names at https://github.com/r3peat/BDO_LuaFiles

+ [ ] How i can get list of functions loaded from `Debug Lua Console` ? 
+ [ ] How i can close debug from in game typing something at `Debug Lua Console` ? 

---

_i got opened panes, close , declare variables, but i really don't know the power of this, can you guide me , please @r3peat_

_close this issue at read_

**Comment by r3peat** [comment]
figure it out. im not a teacher

**Comment by netzulo** [comment]
totally agree
