### ISSUE TITLE
[Feature] AutoRepairHack

### ISSUE THREAD

**Issue by netzulo** [r3peat/R3p.BDO#33]
## Description

A new functionality what allow to repair **horse/ship/player** items from anywhere

- Can access to this GUI **panel** from *game-client* using luadebug.lua : 
``` lua
Panel_Window_Repair:SetShow(true)
```
- When use GUI buttons, this message is showed : **`Character does not exist`**
- **TODO**: Don't know how to call buttons directly

### SPECs

+ Add new key to settings names `AutoRepairHack` (*modify bdo and bdo.settings*)
+ Can be set at settings like this 
``` xml
<AutoRepairHack PlayerInventory="1" PlayerHorse="1" PlayerShip="1" />
```

---

*Im really new with lua lang, of course im losing many things, sorry for this... , can you help to me to fill up SPECs , need code guidelines from you to develop this, @r3peat*

**Comment by r3peat** [comment]
dno. check the lua code how it works but it prbly wont work when there is no repair npc nearby

**Comment by netzulo** [comment]
okeyyy !  thank you very much ! ^^
