### ISSUE TITLE
[Question] How to test and apply to other games.

### ISSUE THREAD

**Issue by legendarynacar** [r3peat/R3p.BDO#35]
Hey,

I played bdo for 2 weeks in gamezbd to learn and explore. Had fun and quit. Maybe I will be back, not sure yet.

So my first question is; how am can I do tests while not sacrificing my hwid, account etc on gamezbd. The reason for testing is to understand how it is working and learning new algorithms for AI bots.

My second question is; is it possible to implement/modify it for another type of game. For instance I want to try it on Silkroad Online (old mmorpg) both official and pserver.

Thanks in advance.

**Comment by r3peat** [comment]
1. just dont mess with stuff which is checked on client side or on server side, the later one u never know until it happens

2. no
