### ISSUE TITLE
Debug from VS2017 ?

### ISSUE THREAD

**Issue by netzulo** [r3peat/R3p.BDO#6]
## Description

It's not working development debug from VS2017. Need to create FTP creeds to use or get real paths at **current host** with binaries.

### SPECs

+ [ ] Setteable FTP server from UI
+ [ ] Add *OR* for FTP , need to load from different **Debug/** directories
+ [ ] When **OR** is't ready, get setteable path from UI
+ [ ] Create builds from windows CI (_using fork url_) : https://ci.appveyor.com/project/netzulo/r3p-bdo

**Comment by netzulo** [comment]
can i edit the UI ?

**Comment by r3peat** [comment]
i dont get the issue here sry

**Comment by netzulo** [comment]
give me some days to fix this :) just it's project settings configuration for VS2017, after this, will can stop game from VS2017 to debug correctly your library with runtime BDO proccess

**Comment by netzulo** [comment]
will resolve from another way, closed at this point! ty !
